// Code generated by "stringer -type=Hand"; DO NOT EDIT.

package rock_paper_scissors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ROCK-0]
	_ = x[PPDER-1]
	_ = x[SCISSORS-2]
}

const _Hand_name = "ROCKPPDERSCISSORS"

var _Hand_index = [...]uint8{0, 4, 9, 17}

func (i Hand) String() string {
	if i < 0 || i >= Hand(len(_Hand_index)-1) {
		return "Hand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hand_name[_Hand_index[i]:_Hand_index[i+1]]
}
